/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CalculationMethod;
import io.xr.lab.shared.dto.CreateCalculationMethodRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.UpdateCalculationMethodRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-20T13:31:51.674991500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "calculation-methods", description = "the calculation-methods API")
public interface CalculationMethodsApi {

  String PATH_CALCULATION_RULES_CREATE_CALCULATION_RULE = "/api/calculation-methods";

  /**
   * POST /api/calculation-methods
   *
   * @param createCalculationMethodRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationMethodsCreateCalculationMethod",
      tags = {"calculation-methods"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationMethod.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = CalculationMethodsApi.PATH_CALCULATION_RULES_CREATE_CALCULATION_RULE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<CalculationMethod> calculationMethodsCreateCalculationMethod(
      @Parameter(name = "CreateCalculationMethodRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCalculationMethodRequest createCalculationMethodRequest);

  String PATH_CALCULATION_RULES_DELETE_CALCULATION_RULE =
      "/api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * DELETE /api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "calculationMethodsDeleteCalculationMethod",
      tags = {"calculation-methods"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = CalculationMethodsApi.PATH_CALCULATION_RULES_DELETE_CALCULATION_RULE,
      produces = {"application/json"})
  ResponseEntity<Void> calculationMethodsDeleteCalculationMethod(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_GET_CALCULATION_RULE =
      "/api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * GET /api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationMethodsGetCalculationMethod",
      tags = {"calculation-methods"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationMethod.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = CalculationMethodsApi.PATH_CALCULATION_RULES_GET_CALCULATION_RULE,
      produces = {"application/json"})
  ResponseEntity<CalculationMethod> calculationMethodsGetCalculationMethod(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_LIST_CALCULATION_RULES = "/api/calculation-methods";

  /**
   * GET /api/calculation-methods
   *
   * @param inspectionObjectCode (optional)
   * @param inspectionParameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationMethodsListCalculationMethods",
      tags = {"calculation-methods"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = CalculationMethod.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = CalculationMethodsApi.PATH_CALCULATION_RULES_LIST_CALCULATION_RULES,
      produces = {"application/json"})
  ResponseEntity<List<CalculationMethod>> calculationMethodsListCalculationMethods(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionParameterCode", required = false)
          @Nullable
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_UPDATE_CALCULATION_RULE =
      "/api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * PUT /api/calculation-methods/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @param updateCalculationMethodRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationMethodsUpdateCalculationMethod",
      tags = {"calculation-methods"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationMethod.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = CalculationMethodsApi.PATH_CALCULATION_RULES_UPDATE_CALCULATION_RULE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<CalculationMethod> calculationMethodsUpdateCalculationMethod(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode,
      @Parameter(name = "UpdateCalculationMethodRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCalculationMethodRequest updateCalculationMethodRequest);
}
