/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CalculationRule;
import io.xr.lab.shared.dto.CreateCalculationRuleRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.UpdateCalculationRuleRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-19T17:37:44.319774200+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "calculation-rules", description = "the calculation-rules API")
public interface CalculationRulesApi {

  String PATH_CALCULATION_RULES_CREATE_CALCULATION_RULE = "/api/calculation-rules";

  /**
   * POST /api/calculation-rules
   *
   * @param createCalculationRuleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationRulesCreateCalculationRule",
      tags = {"calculation-rules"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationRule.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = CalculationRulesApi.PATH_CALCULATION_RULES_CREATE_CALCULATION_RULE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<CalculationRule> calculationRulesCreateCalculationRule(
      @Parameter(name = "CreateCalculationRuleRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCalculationRuleRequest createCalculationRuleRequest);

  String PATH_CALCULATION_RULES_DELETE_CALCULATION_RULE =
      "/api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * DELETE /api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "calculationRulesDeleteCalculationRule",
      tags = {"calculation-rules"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = CalculationRulesApi.PATH_CALCULATION_RULES_DELETE_CALCULATION_RULE,
      produces = {"application/json"})
  ResponseEntity<Void> calculationRulesDeleteCalculationRule(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_GET_CALCULATION_RULE =
      "/api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * GET /api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationRulesGetCalculationRule",
      tags = {"calculation-rules"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationRule.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = CalculationRulesApi.PATH_CALCULATION_RULES_GET_CALCULATION_RULE,
      produces = {"application/json"})
  ResponseEntity<CalculationRule> calculationRulesGetCalculationRule(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_LIST_CALCULATION_RULES = "/api/calculation-rules";

  /**
   * GET /api/calculation-rules
   *
   * @param inspectionObjectCode (optional)
   * @param inspectionParameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationRulesListCalculationRules",
      tags = {"calculation-rules"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = CalculationRule.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = CalculationRulesApi.PATH_CALCULATION_RULES_LIST_CALCULATION_RULES,
      produces = {"application/json"})
  ResponseEntity<List<CalculationRule>> calculationRulesListCalculationRules(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionParameterCode", required = false)
          @Nullable
          String inspectionParameterCode);

  String PATH_CALCULATION_RULES_UPDATE_CALCULATION_RULE =
      "/api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}";

  /**
   * PUT /api/calculation-rules/{inspectionObjectCode}/{inspectionParameterCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @param updateCalculationRuleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "calculationRulesUpdateCalculationRule",
      tags = {"calculation-rules"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CalculationRule.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = CalculationRulesApi.PATH_CALCULATION_RULES_UPDATE_CALCULATION_RULE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<CalculationRule> calculationRulesUpdateCalculationRule(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode,
      @Parameter(name = "UpdateCalculationRuleRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCalculationRuleRequest updateCalculationRuleRequest);
}
