/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.Contract;
import io.xr.lab.shared.dto.ContractStatus;
import io.xr.lab.shared.dto.ContractsListContracts200Response;
import io.xr.lab.shared.dto.CreateContractRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.UpdateContractRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-26T12:43:04.549030500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "contracts", description = "the contracts API")
public interface ContractsApi {

  String PATH_CONTRACTS_CREATE_CONTRACT = "/api/contracts";

  /**
   * POST /api/contracts
   *
   * @param createContractRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "contractsCreateContract",
      tags = {"contracts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Contract.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ContractsApi.PATH_CONTRACTS_CREATE_CONTRACT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Contract> contractsCreateContract(
      @Parameter(name = "CreateContractRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateContractRequest createContractRequest);

  String PATH_CONTRACTS_DELETE_CONTRACT = "/api/contracts/{id}";

  /**
   * DELETE /api/contracts/{id}
   *
   * @param id (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "contractsDeleteContract",
      tags = {"contracts"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ContractsApi.PATH_CONTRACTS_DELETE_CONTRACT,
      produces = {"application/json"})
  ResponseEntity<Void> contractsDeleteContract(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_CONTRACTS_GET_CONTRACT = "/api/contracts/{id}";

  /**
   * GET /api/contracts/{id}
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "contractsGetContract",
      tags = {"contracts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Contract.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ContractsApi.PATH_CONTRACTS_GET_CONTRACT,
      produces = {"application/json"})
  ResponseEntity<Contract> contractsGetContract(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_CONTRACTS_LIST_CONTRACTS = "/api/contracts";

  /**
   * GET /api/contracts
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @param status (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "contractsListContracts",
      tags = {"contracts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ContractsListContracts200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ContractsApi.PATH_CONTRACTS_LIST_CONTRACTS,
      produces = {"application/json"})
  ResponseEntity<ContractsListContracts200Response> contractsListContracts(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword,
      @Parameter(name = "status", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "status", required = false)
          @Nullable
          ContractStatus status);

  String PATH_CONTRACTS_UPDATE_CONTRACT = "/api/contracts/{id}";

  /**
   * PUT /api/contracts/{id}
   *
   * @param id (required)
   * @param updateContractRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "contractsUpdateContract",
      tags = {"contracts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Contract.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = ContractsApi.PATH_CONTRACTS_UPDATE_CONTRACT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Contract> contractsUpdateContract(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "UpdateContractRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateContractRequest updateContractRequest);
}
