/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.FrontendBindMetaFrontendBindSnapshot;
import jakarta.annotation.Generated;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-02T21:47:39.355598900+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "frontend-bind-meta", description = "the frontend-bind-meta API")
public interface FrontendBindMetaApi {

  String PATH_FRONTEND_BIND_META_GET_FRONTEND_BIND_SNAPSHOT = "/api/_frontend-bind/snapshot";

  /**
   * GET /api/_frontend-bind/snapshot
   *
   * @return The request has succeeded. (status code 200)
   */
  @Operation(
      operationId = "frontendBindMetaGetFrontendBindSnapshot",
      tags = {"frontend-bind-meta"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = FrontendBindMetaFrontendBindSnapshot.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = FrontendBindMetaApi.PATH_FRONTEND_BIND_META_GET_FRONTEND_BIND_SNAPSHOT,
      produces = {"application/json"})
  ResponseEntity<FrontendBindMetaFrontendBindSnapshot> frontendBindMetaGetFrontendBindSnapshot();
}
