/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateInspectionObjectRequest;
import io.xr.lab.shared.dto.CreateInspectionParameterRequest;
import io.xr.lab.shared.dto.CreateInspectionSpecialtyRequest;
import io.xr.lab.shared.dto.CreateInspectionStandardRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.InspectionDictionaryListObjectParameterLinks200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListObjectStandardLinks200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListObjects200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListParameters200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListSpecialties200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListSpecialtyObjectLinks200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListStandardParameterLinks200Response;
import io.xr.lab.shared.dto.InspectionDictionaryListStandards200Response;
import io.xr.lab.shared.dto.InspectionDictionaryUnlinkObjectParameterRequest;
import io.xr.lab.shared.dto.InspectionDictionaryUnlinkObjectStandardRequest;
import io.xr.lab.shared.dto.InspectionObject;
import io.xr.lab.shared.dto.InspectionParameter;
import io.xr.lab.shared.dto.InspectionParameterSourceType;
import io.xr.lab.shared.dto.InspectionSpecialty;
import io.xr.lab.shared.dto.InspectionStandard;
import io.xr.lab.shared.dto.InspectionStandardRole;
import io.xr.lab.shared.dto.InspectionStandardStatus;
import io.xr.lab.shared.dto.ObjectParameterLink;
import io.xr.lab.shared.dto.ObjectStandardLink;
import io.xr.lab.shared.dto.SpecialtyObjectLink;
import io.xr.lab.shared.dto.StandardParameterLink;
import io.xr.lab.shared.dto.UpdateInspectionObjectRequest;
import io.xr.lab.shared.dto.UpdateInspectionParameterRequest;
import io.xr.lab.shared.dto.UpdateInspectionSpecialtyRequest;
import io.xr.lab.shared.dto.UpdateInspectionStandardRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-02T21:47:39.355598900+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "inspection-dictionary", description = "the inspection-dictionary API")
public interface InspectionDictionaryApi {

  String PATH_INSPECTION_DICTIONARY_CREATE_OBJECT = "/api/inspection/objects";

  /**
   * POST /api/inspection/objects
   *
   * @param createInspectionObjectRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryCreateObject",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionObject.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_CREATE_OBJECT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionObject> inspectionDictionaryCreateObject(
      @Parameter(name = "CreateInspectionObjectRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateInspectionObjectRequest createInspectionObjectRequest);

  String PATH_INSPECTION_DICTIONARY_CREATE_PARAMETER = "/api/inspection/parameters";

  /**
   * POST /api/inspection/parameters
   *
   * @param createInspectionParameterRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryCreateParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionParameter.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_CREATE_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionParameter> inspectionDictionaryCreateParameter(
      @Parameter(name = "CreateInspectionParameterRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateInspectionParameterRequest createInspectionParameterRequest);

  String PATH_INSPECTION_DICTIONARY_CREATE_SPECIALTY = "/api/inspection/specialties";

  /**
   * POST /api/inspection/specialties
   *
   * @param createInspectionSpecialtyRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryCreateSpecialty",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionSpecialty.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_CREATE_SPECIALTY,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionSpecialty> inspectionDictionaryCreateSpecialty(
      @Parameter(name = "CreateInspectionSpecialtyRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateInspectionSpecialtyRequest createInspectionSpecialtyRequest);

  String PATH_INSPECTION_DICTIONARY_CREATE_STANDARD = "/api/inspection/standards";

  /**
   * POST /api/inspection/standards
   *
   * @param createInspectionStandardRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryCreateStandard",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionStandard.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_CREATE_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionStandard> inspectionDictionaryCreateStandard(
      @Parameter(name = "CreateInspectionStandardRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateInspectionStandardRequest createInspectionStandardRequest);

  String PATH_INSPECTION_DICTIONARY_DELETE_OBJECT = "/api/inspection/objects/{code}";

  /**
   * DELETE /api/inspection/objects/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryDeleteObject",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_DELETE_OBJECT,
      produces = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryDeleteObject(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_INSPECTION_DICTIONARY_DELETE_PARAMETER = "/api/inspection/parameters/{code}";

  /**
   * DELETE /api/inspection/parameters/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryDeleteParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_DELETE_PARAMETER,
      produces = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryDeleteParameter(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_INSPECTION_DICTIONARY_DELETE_SPECIALTY = "/api/inspection/specialties/{code}";

  /**
   * DELETE /api/inspection/specialties/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryDeleteSpecialty",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_DELETE_SPECIALTY,
      produces = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryDeleteSpecialty(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_INSPECTION_DICTIONARY_DELETE_STANDARD = "/api/inspection/standards/{code}";

  /**
   * DELETE /api/inspection/standards/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryDeleteStandard",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_DELETE_STANDARD,
      produces = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryDeleteStandard(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_INSPECTION_DICTIONARY_LINK_OBJECT_PARAMETER =
      "/api/inspection/links/object-parameter";

  /**
   * POST /api/inspection/links/object-parameter
   *
   * @param objectParameterLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryLinkObjectParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LINK_OBJECT_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryLinkObjectParameter(
      @Parameter(name = "ObjectParameterLink", description = "", required = true)
          @Valid
          @RequestBody
          ObjectParameterLink objectParameterLink);

  String PATH_INSPECTION_DICTIONARY_LINK_OBJECT_STANDARD = "/api/inspection/links/object-standard";

  /**
   * POST /api/inspection/links/object-standard
   *
   * @param objectStandardLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryLinkObjectStandard",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LINK_OBJECT_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryLinkObjectStandard(
      @Parameter(name = "ObjectStandardLink", description = "", required = true) @Valid @RequestBody
          ObjectStandardLink objectStandardLink);

  String PATH_INSPECTION_DICTIONARY_LINK_SPECIALTY_OBJECT =
      "/api/inspection/links/specialty-object";

  /**
   * POST /api/inspection/links/specialty-object
   *
   * @param specialtyObjectLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryLinkSpecialtyObject",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LINK_SPECIALTY_OBJECT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryLinkSpecialtyObject(
      @Parameter(name = "SpecialtyObjectLink", description = "", required = true)
          @Valid
          @RequestBody
          SpecialtyObjectLink specialtyObjectLink);

  String PATH_INSPECTION_DICTIONARY_LINK_STANDARD_PARAMETER =
      "/api/inspection/links/standard-parameter";

  /**
   * POST /api/inspection/links/standard-parameter
   *
   * @param standardParameterLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryLinkStandardParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LINK_STANDARD_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryLinkStandardParameter(
      @Parameter(name = "StandardParameterLink", description = "", required = true)
          @Valid
          @RequestBody
          StandardParameterLink standardParameterLink);

  String PATH_INSPECTION_DICTIONARY_LIST_OBJECT_PARAMETER_LINKS =
      "/api/inspection/links/object-parameter";

  /**
   * GET /api/inspection/links/object-parameter
   *
   * @param inspectionObjectCode (optional)
   * @param inspectionParameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListObjectParameterLinks",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation =
                              InspectionDictionaryListObjectParameterLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_OBJECT_PARAMETER_LINKS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListObjectParameterLinks200Response>
      inspectionDictionaryListObjectParameterLinks(
          @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionObjectCode", required = false)
              @Nullable
              String inspectionObjectCode,
          @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionParameterCode", required = false)
              @Nullable
              String inspectionParameterCode);

  String PATH_INSPECTION_DICTIONARY_LIST_OBJECT_STANDARD_LINKS =
      "/api/inspection/links/object-standard";

  /**
   * GET /api/inspection/links/object-standard
   *
   * @param inspectionObjectCode (optional)
   * @param role (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListObjectStandardLinks",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation =
                              InspectionDictionaryListObjectStandardLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_OBJECT_STANDARD_LINKS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListObjectStandardLinks200Response>
      inspectionDictionaryListObjectStandardLinks(
          @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionObjectCode", required = false)
              @Nullable
              String inspectionObjectCode,
          @Parameter(name = "role", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "role", required = false)
              @Nullable
              InspectionStandardRole role);

  String PATH_INSPECTION_DICTIONARY_LIST_OBJECTS = "/api/inspection/objects";

  /**
   * GET /api/inspection/objects
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param inspectionSpecialtyCode (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListObjects",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(implementation = InspectionDictionaryListObjects200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_OBJECTS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListObjects200Response> inspectionDictionaryListObjects(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "inspectionSpecialtyCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionSpecialtyCode", required = false)
          @Nullable
          String inspectionSpecialtyCode,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_INSPECTION_DICTIONARY_LIST_PARAMETERS = "/api/inspection/parameters";

  /**
   * GET /api/inspection/parameters
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @param sourceType (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListParameters",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(implementation = InspectionDictionaryListParameters200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_PARAMETERS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListParameters200Response> inspectionDictionaryListParameters(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword,
      @Parameter(name = "sourceType", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "sourceType", required = false)
          @Nullable
          InspectionParameterSourceType sourceType);

  String PATH_INSPECTION_DICTIONARY_LIST_SPECIALTIES = "/api/inspection/specialties";

  /**
   * GET /api/inspection/specialties
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListSpecialties",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation = InspectionDictionaryListSpecialties200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_SPECIALTIES,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListSpecialties200Response>
      inspectionDictionaryListSpecialties(
          @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "page", required = false)
              @Nullable
              Integer page,
          @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "pageSize", required = false)
              @Nullable
              Integer pageSize,
          @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "keyword", required = false)
              @Nullable
              String keyword);

  String PATH_INSPECTION_DICTIONARY_LIST_SPECIALTY_OBJECT_LINKS =
      "/api/inspection/links/specialty-object";

  /**
   * GET /api/inspection/links/specialty-object
   *
   * @param inspectionSpecialtyCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListSpecialtyObjectLinks",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation =
                              InspectionDictionaryListSpecialtyObjectLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_SPECIALTY_OBJECT_LINKS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListSpecialtyObjectLinks200Response>
      inspectionDictionaryListSpecialtyObjectLinks(
          @Parameter(name = "inspectionSpecialtyCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionSpecialtyCode", required = false)
              @Nullable
              String inspectionSpecialtyCode);

  String PATH_INSPECTION_DICTIONARY_LIST_STANDARD_PARAMETER_LINKS =
      "/api/inspection/links/standard-parameter";

  /**
   * GET /api/inspection/links/standard-parameter
   *
   * @param inspectionStandardCode (optional)
   * @param inspectionParameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListStandardParameterLinks",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation =
                              InspectionDictionaryListStandardParameterLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_STANDARD_PARAMETER_LINKS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListStandardParameterLinks200Response>
      inspectionDictionaryListStandardParameterLinks(
          @Parameter(name = "inspectionStandardCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionStandardCode", required = false)
              @Nullable
              String inspectionStandardCode,
          @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionParameterCode", required = false)
              @Nullable
              String inspectionParameterCode);

  String PATH_INSPECTION_DICTIONARY_LIST_STANDARDS = "/api/inspection/standards";

  /**
   * GET /api/inspection/standards
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @param status (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryListStandards",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(implementation = InspectionDictionaryListStandards200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_LIST_STANDARDS,
      produces = {"application/json"})
  ResponseEntity<InspectionDictionaryListStandards200Response> inspectionDictionaryListStandards(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword,
      @Parameter(name = "status", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "status", required = false)
          @Nullable
          InspectionStandardStatus status);

  String PATH_INSPECTION_DICTIONARY_UNLINK_OBJECT_PARAMETER =
      "/api/inspection/links/object-parameter";

  /**
   * DELETE /api/inspection/links/object-parameter
   *
   * @param inspectionDictionaryUnlinkObjectParameterRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUnlinkObjectParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UNLINK_OBJECT_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryUnlinkObjectParameter(
      @Parameter(
              name = "InspectionDictionaryUnlinkObjectParameterRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          InspectionDictionaryUnlinkObjectParameterRequest
              inspectionDictionaryUnlinkObjectParameterRequest);

  String PATH_INSPECTION_DICTIONARY_UNLINK_OBJECT_STANDARD =
      "/api/inspection/links/object-standard";

  /**
   * DELETE /api/inspection/links/object-standard
   *
   * @param inspectionDictionaryUnlinkObjectStandardRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUnlinkObjectStandard",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UNLINK_OBJECT_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryUnlinkObjectStandard(
      @Parameter(
              name = "InspectionDictionaryUnlinkObjectStandardRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          InspectionDictionaryUnlinkObjectStandardRequest
              inspectionDictionaryUnlinkObjectStandardRequest);

  String PATH_INSPECTION_DICTIONARY_UNLINK_SPECIALTY_OBJECT =
      "/api/inspection/links/specialty-object";

  /**
   * DELETE /api/inspection/links/specialty-object
   *
   * @param specialtyObjectLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUnlinkSpecialtyObject",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UNLINK_SPECIALTY_OBJECT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryUnlinkSpecialtyObject(
      @Parameter(name = "SpecialtyObjectLink", description = "", required = true)
          @Valid
          @RequestBody
          SpecialtyObjectLink specialtyObjectLink);

  String PATH_INSPECTION_DICTIONARY_UNLINK_STANDARD_PARAMETER =
      "/api/inspection/links/standard-parameter";

  /**
   * DELETE /api/inspection/links/standard-parameter
   *
   * @param standardParameterLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUnlinkStandardParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UNLINK_STANDARD_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> inspectionDictionaryUnlinkStandardParameter(
      @Parameter(name = "StandardParameterLink", description = "", required = true)
          @Valid
          @RequestBody
          StandardParameterLink standardParameterLink);

  String PATH_INSPECTION_DICTIONARY_UPDATE_OBJECT = "/api/inspection/objects/{code}";

  /**
   * PUT /api/inspection/objects/{code}
   *
   * @param code (required)
   * @param updateInspectionObjectRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUpdateObject",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionObject.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UPDATE_OBJECT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionObject> inspectionDictionaryUpdateObject(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateInspectionObjectRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateInspectionObjectRequest updateInspectionObjectRequest);

  String PATH_INSPECTION_DICTIONARY_UPDATE_PARAMETER = "/api/inspection/parameters/{code}";

  /**
   * PUT /api/inspection/parameters/{code}
   *
   * @param code (required)
   * @param updateInspectionParameterRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUpdateParameter",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionParameter.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UPDATE_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionParameter> inspectionDictionaryUpdateParameter(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateInspectionParameterRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateInspectionParameterRequest updateInspectionParameterRequest);

  String PATH_INSPECTION_DICTIONARY_UPDATE_SPECIALTY = "/api/inspection/specialties/{code}";

  /**
   * PUT /api/inspection/specialties/{code}
   *
   * @param code (required)
   * @param updateInspectionSpecialtyRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUpdateSpecialty",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionSpecialty.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UPDATE_SPECIALTY,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionSpecialty> inspectionDictionaryUpdateSpecialty(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateInspectionSpecialtyRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateInspectionSpecialtyRequest updateInspectionSpecialtyRequest);

  String PATH_INSPECTION_DICTIONARY_UPDATE_STANDARD = "/api/inspection/standards/{code}";

  /**
   * PUT /api/inspection/standards/{code}
   *
   * @param code (required)
   * @param updateInspectionStandardRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "inspectionDictionaryUpdateStandard",
      tags = {"inspection-dictionary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionStandard.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionDictionaryApi.PATH_INSPECTION_DICTIONARY_UPDATE_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionStandard> inspectionDictionaryUpdateStandard(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateInspectionStandardRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateInspectionStandardRequest updateInspectionStandardRequest);
}
