/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateCatalogEntryRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.InspectionBrand;
import io.xr.lab.shared.dto.InspectionGrade;
import io.xr.lab.shared.dto.InspectionModel;
import io.xr.lab.shared.dto.InspectionSpec;
import io.xr.lab.shared.dto.UpdateCatalogEntryRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-19T17:37:44.319774200+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "inspection-catalog", description = "the inspection-catalog API")
public interface InspectionCatalogApi {

  String PATH_CATALOG_CREATE_BRAND = "/api/catalog/brands";

  /**
   * POST /api/catalog/brands
   *
   * @param createCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogCreateBrand",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionBrand.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionCatalogApi.PATH_CATALOG_CREATE_BRAND,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionBrand> catalogCreateBrand(
      @Parameter(name = "CreateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCatalogEntryRequest createCatalogEntryRequest);

  String PATH_CATALOG_CREATE_GRADE = "/api/catalog/grades";

  /**
   * POST /api/catalog/grades
   *
   * @param createCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogCreateGrade",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionGrade.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionCatalogApi.PATH_CATALOG_CREATE_GRADE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionGrade> catalogCreateGrade(
      @Parameter(name = "CreateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCatalogEntryRequest createCatalogEntryRequest);

  String PATH_CATALOG_CREATE_MODEL = "/api/catalog/models";

  /**
   * POST /api/catalog/models
   *
   * @param createCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogCreateModel",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionModel.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionCatalogApi.PATH_CATALOG_CREATE_MODEL,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionModel> catalogCreateModel(
      @Parameter(name = "CreateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCatalogEntryRequest createCatalogEntryRequest);

  String PATH_CATALOG_CREATE_SPEC = "/api/catalog/specs";

  /**
   * POST /api/catalog/specs
   *
   * @param createCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogCreateSpec",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionSpec.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = InspectionCatalogApi.PATH_CATALOG_CREATE_SPEC,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionSpec> catalogCreateSpec(
      @Parameter(name = "CreateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateCatalogEntryRequest createCatalogEntryRequest);

  String PATH_CATALOG_DELETE_BRAND = "/api/catalog/brands/{code}";

  /**
   * DELETE /api/catalog/brands/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "catalogDeleteBrand",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionCatalogApi.PATH_CATALOG_DELETE_BRAND,
      produces = {"application/json"})
  ResponseEntity<Void> catalogDeleteBrand(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_CATALOG_DELETE_GRADE = "/api/catalog/grades/{code}";

  /**
   * DELETE /api/catalog/grades/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "catalogDeleteGrade",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionCatalogApi.PATH_CATALOG_DELETE_GRADE,
      produces = {"application/json"})
  ResponseEntity<Void> catalogDeleteGrade(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_CATALOG_DELETE_MODEL = "/api/catalog/models/{code}";

  /**
   * DELETE /api/catalog/models/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "catalogDeleteModel",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionCatalogApi.PATH_CATALOG_DELETE_MODEL,
      produces = {"application/json"})
  ResponseEntity<Void> catalogDeleteModel(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_CATALOG_DELETE_SPEC = "/api/catalog/specs/{code}";

  /**
   * DELETE /api/catalog/specs/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "catalogDeleteSpec",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = InspectionCatalogApi.PATH_CATALOG_DELETE_SPEC,
      produces = {"application/json"})
  ResponseEntity<Void> catalogDeleteSpec(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_CATALOG_LIST_BRANDS = "/api/catalog/brands";

  /**
   * GET /api/catalog/brands
   *
   * @param inspectionObjectCode (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogListBrands",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = InspectionBrand.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionCatalogApi.PATH_CATALOG_LIST_BRANDS,
      produces = {"application/json"})
  ResponseEntity<List<InspectionBrand>> catalogListBrands(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_CATALOG_LIST_GRADES = "/api/catalog/grades";

  /**
   * GET /api/catalog/grades
   *
   * @param inspectionObjectCode (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogListGrades",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = InspectionGrade.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionCatalogApi.PATH_CATALOG_LIST_GRADES,
      produces = {"application/json"})
  ResponseEntity<List<InspectionGrade>> catalogListGrades(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_CATALOG_LIST_MODELS = "/api/catalog/models";

  /**
   * GET /api/catalog/models
   *
   * @param inspectionObjectCode (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogListModels",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = InspectionModel.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionCatalogApi.PATH_CATALOG_LIST_MODELS,
      produces = {"application/json"})
  ResponseEntity<List<InspectionModel>> catalogListModels(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_CATALOG_LIST_SPECS = "/api/catalog/specs";

  /**
   * GET /api/catalog/specs
   *
   * @param inspectionObjectCode (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogListSpecs",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = InspectionSpec.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = InspectionCatalogApi.PATH_CATALOG_LIST_SPECS,
      produces = {"application/json"})
  ResponseEntity<List<InspectionSpec>> catalogListSpecs(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_CATALOG_UPDATE_BRAND = "/api/catalog/brands/{code}";

  /**
   * PUT /api/catalog/brands/{code}
   *
   * @param code (required)
   * @param updateCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogUpdateBrand",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionBrand.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionCatalogApi.PATH_CATALOG_UPDATE_BRAND,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionBrand> catalogUpdateBrand(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCatalogEntryRequest updateCatalogEntryRequest);

  String PATH_CATALOG_UPDATE_GRADE = "/api/catalog/grades/{code}";

  /**
   * PUT /api/catalog/grades/{code}
   *
   * @param code (required)
   * @param updateCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogUpdateGrade",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionGrade.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionCatalogApi.PATH_CATALOG_UPDATE_GRADE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionGrade> catalogUpdateGrade(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCatalogEntryRequest updateCatalogEntryRequest);

  String PATH_CATALOG_UPDATE_MODEL = "/api/catalog/models/{code}";

  /**
   * PUT /api/catalog/models/{code}
   *
   * @param code (required)
   * @param updateCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogUpdateModel",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionModel.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionCatalogApi.PATH_CATALOG_UPDATE_MODEL,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionModel> catalogUpdateModel(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCatalogEntryRequest updateCatalogEntryRequest);

  String PATH_CATALOG_UPDATE_SPEC = "/api/catalog/specs/{code}";

  /**
   * PUT /api/catalog/specs/{code}
   *
   * @param code (required)
   * @param updateCatalogEntryRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "catalogUpdateSpec",
      tags = {"inspection-catalog"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionSpec.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = InspectionCatalogApi.PATH_CATALOG_UPDATE_SPEC,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionSpec> catalogUpdateSpec(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateCatalogEntryRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateCatalogEntryRequest updateCatalogEntryRequest);
}
