/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.AssignTaskRequest;
import io.xr.lab.shared.dto.CreateSampleReceiptRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.FlowHistoryEntry;
import io.xr.lab.shared.dto.FlowStatus;
import io.xr.lab.shared.dto.ReceiptsListReceipts200Response;
import io.xr.lab.shared.dto.SampleReceipt;
import io.xr.lab.shared.dto.UpdateSampleReceiptRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-18T09:31:54.550738400+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "receipts", description = "the receipts API")
public interface ReceiptsApi {

  String PATH_RECEIPTS_ASSIGN_TASK = "/api/receipts/{id}/task";

  /**
   * PUT /api/receipts/{id}/task
   *
   * @param id (required)
   * @param assignTaskRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsAssignTask",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SampleReceipt.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = ReceiptsApi.PATH_RECEIPTS_ASSIGN_TASK,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<SampleReceipt> receiptsAssignTask(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "AssignTaskRequest", description = "", required = true) @Valid @RequestBody
          AssignTaskRequest assignTaskRequest);

  String PATH_RECEIPTS_CREATE_RECEIPT = "/api/receipts";

  /**
   * POST /api/receipts
   *
   * @param createSampleReceiptRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsCreateReceipt",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SampleReceipt.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ReceiptsApi.PATH_RECEIPTS_CREATE_RECEIPT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<SampleReceipt> receiptsCreateReceipt(
      @Parameter(name = "CreateSampleReceiptRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateSampleReceiptRequest createSampleReceiptRequest);

  String PATH_RECEIPTS_DELETE_RECEIPT = "/api/receipts/{id}";

  /**
   * DELETE /api/receipts/{id}
   *
   * @param id (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "receiptsDeleteReceipt",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ReceiptsApi.PATH_RECEIPTS_DELETE_RECEIPT,
      produces = {"application/json"})
  ResponseEntity<Void> receiptsDeleteReceipt(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_RECEIPTS_GET_RECEIPT = "/api/receipts/{id}";

  /**
   * GET /api/receipts/{id}
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsGetReceipt",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SampleReceipt.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReceiptsApi.PATH_RECEIPTS_GET_RECEIPT,
      produces = {"application/json"})
  ResponseEntity<SampleReceipt> receiptsGetReceipt(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_RECEIPTS_GET_RECEIPT_HISTORY = "/api/receipts/{id}/history";

  /**
   * GET /api/receipts/{id}/history
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsGetReceiptHistory",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = FlowHistoryEntry.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReceiptsApi.PATH_RECEIPTS_GET_RECEIPT_HISTORY,
      produces = {"application/json"})
  ResponseEntity<List<FlowHistoryEntry>> receiptsGetReceiptHistory(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_RECEIPTS_LIST_RECEIPTS = "/api/receipts";

  /**
   * GET /api/receipts
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @param contractId (optional)
   * @param flowStatus (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsListReceipts",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ReceiptsListReceipts200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReceiptsApi.PATH_RECEIPTS_LIST_RECEIPTS,
      produces = {"application/json"})
  ResponseEntity<ReceiptsListReceipts200Response> receiptsListReceipts(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword,
      @Parameter(name = "contractId", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "contractId", required = false)
          @Nullable
          String contractId,
      @Parameter(name = "flowStatus", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "flowStatus", required = false)
          @Nullable
          FlowStatus flowStatus);

  String PATH_RECEIPTS_UPDATE_RECEIPT = "/api/receipts/{id}";

  /**
   * PUT /api/receipts/{id}
   *
   * @param id (required)
   * @param updateSampleReceiptRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "receiptsUpdateReceipt",
      tags = {"receipts"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SampleReceipt.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = ReceiptsApi.PATH_RECEIPTS_UPDATE_RECEIPT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<SampleReceipt> receiptsUpdateReceipt(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "UpdateSampleReceiptRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateSampleReceiptRequest updateSampleReceiptRequest);
}
