/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateInspectionReportNameRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.InspectionReportName;
import io.xr.lab.shared.dto.InspectionStandardRole;
import io.xr.lab.shared.dto.ObjectReportNameLink;
import io.xr.lab.shared.dto.ReportNameParameterLink;
import io.xr.lab.shared.dto.ReportNameStandardLink;
import io.xr.lab.shared.dto.ReportNamesListObjectReportNameLinks200Response;
import io.xr.lab.shared.dto.ReportNamesListReportNameParameterLinks200Response;
import io.xr.lab.shared.dto.ReportNamesListReportNameStandardLinks200Response;
import io.xr.lab.shared.dto.ReportNamesListReportNames200Response;
import io.xr.lab.shared.dto.ReportNamesUnlinkObjectReportNameRequest;
import io.xr.lab.shared.dto.ReportNamesUnlinkReportNameParameterRequest;
import io.xr.lab.shared.dto.ReportNamesUnlinkReportNameStandardRequest;
import io.xr.lab.shared.dto.UpdateInspectionReportNameRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-02T21:47:39.355598900+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "report-names", description = "the report-names API")
public interface ReportNamesApi {

  String PATH_REPORT_NAMES_CREATE_REPORT_NAME = "/api/report-names";

  /**
   * POST /api/report-names
   *
   * @param createInspectionReportNameRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesCreateReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionReportName.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ReportNamesApi.PATH_REPORT_NAMES_CREATE_REPORT_NAME,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionReportName> reportNamesCreateReportName(
      @Parameter(name = "CreateInspectionReportNameRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateInspectionReportNameRequest createInspectionReportNameRequest);

  String PATH_REPORT_NAMES_DELETE_REPORT_NAME = "/api/report-names/{code}";

  /**
   * DELETE /api/report-names/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesDeleteReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ReportNamesApi.PATH_REPORT_NAMES_DELETE_REPORT_NAME,
      produces = {"application/json"})
  ResponseEntity<Void> reportNamesDeleteReportName(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_REPORT_NAMES_GET_REPORT_NAME = "/api/report-names/{code}";

  /**
   * GET /api/report-names/{code}
   *
   * @param code (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesGetReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionReportName.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReportNamesApi.PATH_REPORT_NAMES_GET_REPORT_NAME,
      produces = {"application/json"})
  ResponseEntity<InspectionReportName> reportNamesGetReportName(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_REPORT_NAMES_LINK_OBJECT_REPORT_NAME = "/api/report-names/links/object";

  /**
   * POST /api/report-names/links/object
   *
   * @param objectReportNameLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesLinkObjectReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ReportNamesApi.PATH_REPORT_NAMES_LINK_OBJECT_REPORT_NAME,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesLinkObjectReportName(
      @Parameter(name = "ObjectReportNameLink", description = "", required = true)
          @Valid
          @RequestBody
          ObjectReportNameLink objectReportNameLink);

  String PATH_REPORT_NAMES_LINK_REPORT_NAME_PARAMETER = "/api/report-names/links/parameter";

  /**
   * POST /api/report-names/links/parameter
   *
   * @param reportNameParameterLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesLinkReportNameParameter",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ReportNamesApi.PATH_REPORT_NAMES_LINK_REPORT_NAME_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesLinkReportNameParameter(
      @Parameter(name = "ReportNameParameterLink", description = "", required = true)
          @Valid
          @RequestBody
          ReportNameParameterLink reportNameParameterLink);

  String PATH_REPORT_NAMES_LINK_REPORT_NAME_STANDARD = "/api/report-names/links/standard";

  /**
   * POST /api/report-names/links/standard
   *
   * @param reportNameStandardLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesLinkReportNameStandard",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ReportNamesApi.PATH_REPORT_NAMES_LINK_REPORT_NAME_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesLinkReportNameStandard(
      @Parameter(name = "ReportNameStandardLink", description = "", required = true)
          @Valid
          @RequestBody
          ReportNameStandardLink reportNameStandardLink);

  String PATH_REPORT_NAMES_LIST_OBJECT_REPORT_NAME_LINKS = "/api/report-names/links/object";

  /**
   * GET /api/report-names/links/object
   *
   * @param inspectionObjectCode (optional)
   * @param reportNameCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesListObjectReportNameLinks",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation = ReportNamesListObjectReportNameLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReportNamesApi.PATH_REPORT_NAMES_LIST_OBJECT_REPORT_NAME_LINKS,
      produces = {"application/json"})
  ResponseEntity<ReportNamesListObjectReportNameLinks200Response>
      reportNamesListObjectReportNameLinks(
          @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionObjectCode", required = false)
              @Nullable
              String inspectionObjectCode,
          @Parameter(name = "reportNameCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "reportNameCode", required = false)
              @Nullable
              String reportNameCode);

  String PATH_REPORT_NAMES_LIST_REPORT_NAME_PARAMETER_LINKS = "/api/report-names/links/parameter";

  /**
   * GET /api/report-names/links/parameter
   *
   * @param reportNameCode (optional)
   * @param inspectionParameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesListReportNameParameterLinks",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation =
                              ReportNamesListReportNameParameterLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReportNamesApi.PATH_REPORT_NAMES_LIST_REPORT_NAME_PARAMETER_LINKS,
      produces = {"application/json"})
  ResponseEntity<ReportNamesListReportNameParameterLinks200Response>
      reportNamesListReportNameParameterLinks(
          @Parameter(name = "reportNameCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "reportNameCode", required = false)
              @Nullable
              String reportNameCode,
          @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionParameterCode", required = false)
              @Nullable
              String inspectionParameterCode);

  String PATH_REPORT_NAMES_LIST_REPORT_NAME_STANDARD_LINKS = "/api/report-names/links/standard";

  /**
   * GET /api/report-names/links/standard
   *
   * @param reportNameCode (optional)
   * @param role (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesListReportNameStandardLinks",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation = ReportNamesListReportNameStandardLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReportNamesApi.PATH_REPORT_NAMES_LIST_REPORT_NAME_STANDARD_LINKS,
      produces = {"application/json"})
  ResponseEntity<ReportNamesListReportNameStandardLinks200Response>
      reportNamesListReportNameStandardLinks(
          @Parameter(name = "reportNameCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "reportNameCode", required = false)
              @Nullable
              String reportNameCode,
          @Parameter(name = "role", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "role", required = false)
              @Nullable
              InspectionStandardRole role);

  String PATH_REPORT_NAMES_LIST_REPORT_NAMES = "/api/report-names";

  /**
   * GET /api/report-names
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesListReportNames",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ReportNamesListReportNames200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ReportNamesApi.PATH_REPORT_NAMES_LIST_REPORT_NAMES,
      produces = {"application/json"})
  ResponseEntity<ReportNamesListReportNames200Response> reportNamesListReportNames(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_REPORT_NAMES_UNLINK_OBJECT_REPORT_NAME = "/api/report-names/links/object";

  /**
   * DELETE /api/report-names/links/object
   *
   * @param reportNamesUnlinkObjectReportNameRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesUnlinkObjectReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ReportNamesApi.PATH_REPORT_NAMES_UNLINK_OBJECT_REPORT_NAME,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesUnlinkObjectReportName(
      @Parameter(
              name = "ReportNamesUnlinkObjectReportNameRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          ReportNamesUnlinkObjectReportNameRequest reportNamesUnlinkObjectReportNameRequest);

  String PATH_REPORT_NAMES_UNLINK_REPORT_NAME_PARAMETER = "/api/report-names/links/parameter";

  /**
   * DELETE /api/report-names/links/parameter
   *
   * @param reportNamesUnlinkReportNameParameterRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesUnlinkReportNameParameter",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ReportNamesApi.PATH_REPORT_NAMES_UNLINK_REPORT_NAME_PARAMETER,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesUnlinkReportNameParameter(
      @Parameter(
              name = "ReportNamesUnlinkReportNameParameterRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          ReportNamesUnlinkReportNameParameterRequest reportNamesUnlinkReportNameParameterRequest);

  String PATH_REPORT_NAMES_UNLINK_REPORT_NAME_STANDARD = "/api/report-names/links/standard";

  /**
   * DELETE /api/report-names/links/standard
   *
   * @param reportNamesUnlinkReportNameStandardRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "reportNamesUnlinkReportNameStandard",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ReportNamesApi.PATH_REPORT_NAMES_UNLINK_REPORT_NAME_STANDARD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> reportNamesUnlinkReportNameStandard(
      @Parameter(
              name = "ReportNamesUnlinkReportNameStandardRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          ReportNamesUnlinkReportNameStandardRequest reportNamesUnlinkReportNameStandardRequest);

  String PATH_REPORT_NAMES_UPDATE_REPORT_NAME = "/api/report-names/{code}";

  /**
   * PUT /api/report-names/{code}
   *
   * @param code (required)
   * @param updateInspectionReportNameRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "reportNamesUpdateReportName",
      tags = {"report-names"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = InspectionReportName.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = ReportNamesApi.PATH_REPORT_NAMES_UPDATE_REPORT_NAME,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<InspectionReportName> reportNamesUpdateReportName(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateInspectionReportNameRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateInspectionReportNameRequest updateInspectionReportNameRequest);
}
