/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateSampleRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.Sample;
import io.xr.lab.shared.dto.SamplesListSamples200Response;
import io.xr.lab.shared.dto.UpdateSampleRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-26T12:43:04.549030500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "samples", description = "the samples API")
public interface SamplesApi {

  String PATH_SAMPLES_CREATE_SAMPLE = "/api/samples";

  /**
   * POST /api/samples
   *
   * @param createSampleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "samplesCreateSample",
      tags = {"samples"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Sample.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = SamplesApi.PATH_SAMPLES_CREATE_SAMPLE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Sample> samplesCreateSample(
      @Parameter(name = "CreateSampleRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateSampleRequest createSampleRequest);

  String PATH_SAMPLES_DELETE_SAMPLE = "/api/samples/{id}";

  /**
   * DELETE /api/samples/{id}
   *
   * @param id (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "samplesDeleteSample",
      tags = {"samples"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = SamplesApi.PATH_SAMPLES_DELETE_SAMPLE,
      produces = {"application/json"})
  ResponseEntity<Void> samplesDeleteSample(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_SAMPLES_GET_SAMPLE = "/api/samples/{id}";

  /**
   * GET /api/samples/{id}
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "samplesGetSample",
      tags = {"samples"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Sample.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = SamplesApi.PATH_SAMPLES_GET_SAMPLE,
      produces = {"application/json"})
  ResponseEntity<Sample> samplesGetSample(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_SAMPLES_LIST_SAMPLES = "/api/samples";

  /**
   * GET /api/samples
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param receiptId (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "samplesListSamples",
      tags = {"samples"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SamplesListSamples200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = SamplesApi.PATH_SAMPLES_LIST_SAMPLES,
      produces = {"application/json"})
  ResponseEntity<SamplesListSamples200Response> samplesListSamples(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "receiptId", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "receiptId", required = false)
          @Nullable
          String receiptId,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_SAMPLES_UPDATE_SAMPLE = "/api/samples/{id}";

  /**
   * PUT /api/samples/{id}
   *
   * @param id (required)
   * @param updateSampleRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "samplesUpdateSample",
      tags = {"samples"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = Sample.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = SamplesApi.PATH_SAMPLES_UPDATE_SAMPLE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Sample> samplesUpdateSample(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "UpdateSampleRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateSampleRequest updateSampleRequest);
}
