/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.DashboardStats;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.SummaryData;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-26T12:43:04.549030500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "summary", description = "the summary API")
public interface SummaryApi {

  String PATH_SUMMARY_GET_DASHBOARD_STATS = "/api/summary/stats";

  /**
   * GET /api/summary/stats
   *
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "summaryGetDashboardStats",
      tags = {"summary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = DashboardStats.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = SummaryApi.PATH_SUMMARY_GET_DASHBOARD_STATS,
      produces = {"application/json"})
  ResponseEntity<DashboardStats> summaryGetDashboardStats();

  String PATH_SUMMARY_GET_REPORT_SUMMARY = "/api/summary";

  /**
   * GET /api/summary
   *
   * @param categoryCode (optional)
   * @param dateFrom (optional)
   * @param dateTo (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "summaryGetReportSummary",
      tags = {"summary"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SummaryData.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = SummaryApi.PATH_SUMMARY_GET_REPORT_SUMMARY,
      produces = {"application/json"})
  ResponseEntity<SummaryData> summaryGetReportSummary(
      @Parameter(name = "categoryCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "categoryCode", required = false)
          @Nullable
          String categoryCode,
      @Parameter(name = "dateFrom", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "dateFrom", required = false)
          @Nullable
          String dateFrom,
      @Parameter(name = "dateTo", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "dateTo", required = false)
          @Nullable
          String dateTo);
}
