/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateTechnicalRequirementRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.RequirementVerificationStatus;
import io.xr.lab.shared.dto.TechnicalRequirement;
import io.xr.lab.shared.dto.UpdateTechnicalRequirementRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-19T17:37:44.319774200+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "technical-requirements", description = "the technical-requirements API")
public interface TechnicalRequirementsApi {

  String PATH_TECHNICAL_REQUIREMENTS_CREATE_TECHNICAL_REQUIREMENT = "/api/technical-requirements";

  /**
   * POST /api/technical-requirements
   *
   * @param createTechnicalRequirementRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "technicalRequirementsCreateTechnicalRequirement",
      tags = {"technical-requirements"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TechnicalRequirement.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = TechnicalRequirementsApi.PATH_TECHNICAL_REQUIREMENTS_CREATE_TECHNICAL_REQUIREMENT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TechnicalRequirement> technicalRequirementsCreateTechnicalRequirement(
      @Parameter(name = "CreateTechnicalRequirementRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateTechnicalRequirementRequest createTechnicalRequirementRequest);

  String PATH_TECHNICAL_REQUIREMENTS_DELETE_TECHNICAL_REQUIREMENT =
      "/api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}";

  /**
   * DELETE
   * /api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @param judgmentStandardCode (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "technicalRequirementsDeleteTechnicalRequirement",
      tags = {"technical-requirements"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = TechnicalRequirementsApi.PATH_TECHNICAL_REQUIREMENTS_DELETE_TECHNICAL_REQUIREMENT,
      produces = {"application/json"})
  ResponseEntity<Void> technicalRequirementsDeleteTechnicalRequirement(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode,
      @Parameter(
              name = "judgmentStandardCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("judgmentStandardCode")
          String judgmentStandardCode);

  String PATH_TECHNICAL_REQUIREMENTS_GET_TECHNICAL_REQUIREMENT =
      "/api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}";

  /**
   * GET
   * /api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @param judgmentStandardCode (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "technicalRequirementsGetTechnicalRequirement",
      tags = {"technical-requirements"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TechnicalRequirement.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TechnicalRequirementsApi.PATH_TECHNICAL_REQUIREMENTS_GET_TECHNICAL_REQUIREMENT,
      produces = {"application/json"})
  ResponseEntity<TechnicalRequirement> technicalRequirementsGetTechnicalRequirement(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode,
      @Parameter(
              name = "judgmentStandardCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("judgmentStandardCode")
          String judgmentStandardCode);

  String PATH_TECHNICAL_REQUIREMENTS_LIST_TECHNICAL_REQUIREMENTS = "/api/technical-requirements";

  /**
   * GET /api/technical-requirements
   *
   * @param inspectionObjectCode (optional)
   * @param inspectionParameterCode (optional)
   * @param judgmentStandardCode (optional)
   * @param verificationStatus (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "technicalRequirementsListTechnicalRequirements",
      tags = {"technical-requirements"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array =
                      @ArraySchema(schema = @Schema(implementation = TechnicalRequirement.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TechnicalRequirementsApi.PATH_TECHNICAL_REQUIREMENTS_LIST_TECHNICAL_REQUIREMENTS,
      produces = {"application/json"})
  ResponseEntity<List<TechnicalRequirement>> technicalRequirementsListTechnicalRequirements(
      @Parameter(name = "inspectionObjectCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionObjectCode", required = false)
          @Nullable
          String inspectionObjectCode,
      @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "inspectionParameterCode", required = false)
          @Nullable
          String inspectionParameterCode,
      @Parameter(name = "judgmentStandardCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "judgmentStandardCode", required = false)
          @Nullable
          String judgmentStandardCode,
      @Parameter(name = "verificationStatus", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "verificationStatus", required = false)
          @Nullable
          RequirementVerificationStatus verificationStatus);

  String PATH_TECHNICAL_REQUIREMENTS_UPDATE_TECHNICAL_REQUIREMENT =
      "/api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}";

  /**
   * PUT
   * /api/technical-requirements/{inspectionObjectCode}/{inspectionParameterCode}/{judgmentStandardCode}
   *
   * @param inspectionObjectCode (required)
   * @param inspectionParameterCode (required)
   * @param judgmentStandardCode (required)
   * @param updateTechnicalRequirementRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "technicalRequirementsUpdateTechnicalRequirement",
      tags = {"technical-requirements"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TechnicalRequirement.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = TechnicalRequirementsApi.PATH_TECHNICAL_REQUIREMENTS_UPDATE_TECHNICAL_REQUIREMENT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TechnicalRequirement> technicalRequirementsUpdateTechnicalRequirement(
      @Parameter(
              name = "inspectionObjectCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionObjectCode")
          String inspectionObjectCode,
      @Parameter(
              name = "inspectionParameterCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("inspectionParameterCode")
          String inspectionParameterCode,
      @Parameter(
              name = "judgmentStandardCode",
              description = "",
              required = true,
              in = ParameterIn.PATH)
          @PathVariable("judgmentStandardCode")
          String judgmentStandardCode,
      @Parameter(name = "UpdateTechnicalRequirementRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateTechnicalRequirementRequest updateTechnicalRequirementRequest);
}
