/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateTestRecordRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.TestRecord;
import io.xr.lab.shared.dto.TestRecordsListTestRecords200Response;
import io.xr.lab.shared.dto.TestRecordsSetVerdictRequest;
import io.xr.lab.shared.dto.UpdateTestRecordRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-02T21:47:39.355598900+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "test-records", description = "the test-records API")
public interface TestRecordsApi {

  String PATH_TEST_RECORDS_CREATE_TEST_RECORD = "/api/test-records";

  /**
   * POST /api/test-records
   *
   * @param createTestRecordRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "testRecordsCreateTestRecord",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TestRecord.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = TestRecordsApi.PATH_TEST_RECORDS_CREATE_TEST_RECORD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TestRecord> testRecordsCreateTestRecord(
      @Parameter(name = "CreateTestRecordRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateTestRecordRequest createTestRecordRequest);

  String PATH_TEST_RECORDS_DELETE_TEST_RECORD = "/api/test-records/{id}";

  /**
   * DELETE /api/test-records/{id}
   *
   * @param id (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "testRecordsDeleteTestRecord",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = TestRecordsApi.PATH_TEST_RECORDS_DELETE_TEST_RECORD,
      produces = {"application/json"})
  ResponseEntity<Void> testRecordsDeleteTestRecord(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_TEST_RECORDS_GET_TEST_RECORD = "/api/test-records/{id}";

  /**
   * GET /api/test-records/{id}
   *
   * @param id (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "testRecordsGetTestRecord",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TestRecord.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TestRecordsApi.PATH_TEST_RECORDS_GET_TEST_RECORD,
      produces = {"application/json"})
  ResponseEntity<TestRecord> testRecordsGetTestRecord(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id);

  String PATH_TEST_RECORDS_LIST_TEST_RECORDS = "/api/test-records";

  /**
   * GET /api/test-records
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param sampleId (optional)
   * @param parameterCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "testRecordsListTestRecords",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TestRecordsListTestRecords200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = TestRecordsApi.PATH_TEST_RECORDS_LIST_TEST_RECORDS,
      produces = {"application/json"})
  ResponseEntity<TestRecordsListTestRecords200Response> testRecordsListTestRecords(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "sampleId", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "sampleId", required = false)
          @Nullable
          String sampleId,
      @Parameter(name = "parameterCode", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "parameterCode", required = false)
          @Nullable
          String parameterCode);

  String PATH_TEST_RECORDS_SET_VERDICT = "/api/test-records/{id}/verdict";

  /**
   * PATCH /api/test-records/{id}/verdict
   *
   * @param id (required)
   * @param testRecordsSetVerdictRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "testRecordsSetVerdict",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TestRecord.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PATCH,
      value = TestRecordsApi.PATH_TEST_RECORDS_SET_VERDICT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TestRecord> testRecordsSetVerdict(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "TestRecordsSetVerdictRequest", description = "", required = true)
          @Valid
          @RequestBody
          TestRecordsSetVerdictRequest testRecordsSetVerdictRequest);

  String PATH_TEST_RECORDS_UPDATE_TEST_RECORD = "/api/test-records/{id}";

  /**
   * PUT /api/test-records/{id}
   *
   * @param id (required)
   * @param updateTestRecordRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "testRecordsUpdateTestRecord",
      tags = {"test-records"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = TestRecord.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = TestRecordsApi.PATH_TEST_RECORDS_UPDATE_TEST_RECORD,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<TestRecord> testRecordsUpdateTestRecord(
      @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("id")
          String id,
      @Parameter(name = "UpdateTestRecordRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateTestRecordRequest updateTestRecordRequest);
}
