/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.AuthLogoutRequest;
import io.xr.lab.shared.dto.CurrentUserSession;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.LoginRequest;
import io.xr.lab.shared.dto.LoginResponse;
import io.xr.lab.shared.dto.MenuNode;
import io.xr.lab.shared.dto.OAuthResponseType;
import io.xr.lab.shared.dto.PermissionSet;
import io.xr.lab.shared.dto.RefreshTokenRequest;
import io.xr.lab.shared.dto.SsoCallbackRequest;
import io.xr.lab.shared.dto.SsoRedirect;
import io.xr.lab.shared.dto.SwitchTenantRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-04T01:01:08.136686300+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "auth", description = "the auth API")
public interface AuthApi {

  String PATH_AUTH_GET_CURRENT_USER = "/api/auth/me";

  /**
   * GET /api/auth/me
   *
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authGetCurrentUser",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = CurrentUserSession.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AuthApi.PATH_AUTH_GET_CURRENT_USER,
      produces = {"application/json"})
  ResponseEntity<CurrentUserSession> authGetCurrentUser();

  String PATH_AUTH_GET_MENUS = "/api/auth/menus";

  /**
   * GET /api/auth/menus
   *
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authGetMenus",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  array = @ArraySchema(schema = @Schema(implementation = MenuNode.class)))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AuthApi.PATH_AUTH_GET_MENUS,
      produces = {"application/json"})
  ResponseEntity<List<MenuNode>> authGetMenus();

  String PATH_AUTH_GET_PERMISSIONS = "/api/auth/permissions";

  /**
   * GET /api/auth/permissions
   *
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authGetPermissions",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = PermissionSet.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AuthApi.PATH_AUTH_GET_PERMISSIONS,
      produces = {"application/json"})
  ResponseEntity<PermissionSet> authGetPermissions();

  String PATH_AUTH_LOGIN = "/api/auth/login";

  /**
   * POST /api/auth/login
   *
   * @param loginRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authLogin",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_LOGIN,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> authLogin(
      @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody
          LoginRequest loginRequest);

  String PATH_AUTH_LOGOUT = "/api/auth/logout";

  /**
   * POST /api/auth/logout
   *
   * @param authLogoutRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "authLogout",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_LOGOUT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> authLogout(
      @Parameter(name = "AuthLogoutRequest", description = "", required = true) @Valid @RequestBody
          AuthLogoutRequest authLogoutRequest);

  String PATH_AUTH_REFRESH = "/api/auth/refresh";

  /**
   * POST /api/auth/refresh
   *
   * @param refreshTokenRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authRefresh",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_REFRESH,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> authRefresh(
      @Parameter(name = "RefreshTokenRequest", description = "", required = true)
          @Valid
          @RequestBody
          RefreshTokenRequest refreshTokenRequest);

  String PATH_AUTH_SSO_AUTHORIZE = "/api/auth/sso/authorize";

  /**
   * GET /api/auth/sso/authorize
   *
   * @param responseType (required)
   * @param clientId (required)
   * @param redirectUri (required)
   * @param state (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authSsoAuthorize",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = SsoRedirect.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = AuthApi.PATH_AUTH_SSO_AUTHORIZE,
      produces = {"application/json"})
  ResponseEntity<SsoRedirect> authSsoAuthorize(
      @NotNull
          @Parameter(
              name = "response_type",
              description = "",
              required = true,
              in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "response_type", required = true)
          OAuthResponseType responseType,
      @NotNull
          @Parameter(name = "client_id", description = "", required = true, in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "client_id", required = true)
          String clientId,
      @NotNull
          @Parameter(
              name = "redirect_uri",
              description = "",
              required = true,
              in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "redirect_uri", required = true)
          String redirectUri,
      @NotNull
          @Parameter(name = "state", description = "", required = true, in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "state", required = true)
          String state);

  String PATH_AUTH_SSO_CALLBACK = "/api/auth/sso/callback";

  /**
   * POST /api/auth/sso/callback
   *
   * @param ssoCallbackRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authSsoCallback",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_SSO_CALLBACK,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> authSsoCallback(
      @Parameter(name = "SsoCallbackRequest", description = "", required = true) @Valid @RequestBody
          SsoCallbackRequest ssoCallbackRequest);

  String PATH_AUTH_SWITCH_TENANT = "/api/auth/switch-tenant";

  /**
   * POST /api/auth/switch-tenant
   *
   * @param switchTenantRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "authSwitchTenant",
      tags = {"auth"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = LoginResponse.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = AuthApi.PATH_AUTH_SWITCH_TENANT,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<LoginResponse> authSwitchTenant(
      @Parameter(name = "SwitchTenantRequest", description = "", required = true)
          @Valid
          @RequestBody
          SwitchTenantRequest switchTenantRequest);
}
