/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.xr.lab.shared.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.xr.lab.shared.dto.CreateParamInterfaceRequest;
import io.xr.lab.shared.dto.ErrorResponse;
import io.xr.lab.shared.dto.ParamInterface;
import io.xr.lab.shared.dto.ParamInterfaceLink;
import io.xr.lab.shared.dto.ParamInterfacesListParamInterfaceLinks200Response;
import io.xr.lab.shared.dto.ParamInterfacesListParamInterfaces200Response;
import io.xr.lab.shared.dto.ParamInterfacesUnlinkParamInterfaceRequest;
import io.xr.lab.shared.dto.UpdateParamInterfaceRequest;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-09-04T01:01:08.136686300+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "param-interfaces", description = "the param-interfaces API")
public interface ParamInterfacesApi {

  String PATH_PARAM_INTERFACES_CREATE_PARAM_INTERFACE = "/api/param-interfaces";

  /**
   * POST /api/param-interfaces
   *
   * @param createParamInterfaceRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "paramInterfacesCreateParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ParamInterface.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_CREATE_PARAM_INTERFACE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<ParamInterface> paramInterfacesCreateParamInterface(
      @Parameter(name = "CreateParamInterfaceRequest", description = "", required = true)
          @Valid
          @RequestBody
          CreateParamInterfaceRequest createParamInterfaceRequest);

  String PATH_PARAM_INTERFACES_DELETE_PARAM_INTERFACE = "/api/param-interfaces/{code}";

  /**
   * DELETE /api/param-interfaces/{code}
   *
   * @param code (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "paramInterfacesDeleteParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_DELETE_PARAM_INTERFACE,
      produces = {"application/json"})
  ResponseEntity<Void> paramInterfacesDeleteParamInterface(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_PARAM_INTERFACES_GET_PARAM_INTERFACE = "/api/param-interfaces/{code}";

  /**
   * GET /api/param-interfaces/{code}
   *
   * @param code (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "paramInterfacesGetParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ParamInterface.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_GET_PARAM_INTERFACE,
      produces = {"application/json"})
  ResponseEntity<ParamInterface> paramInterfacesGetParamInterface(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code);

  String PATH_PARAM_INTERFACES_LINK_PARAM_INTERFACE = "/api/param-interfaces/links";

  /**
   * POST /api/param-interfaces/links
   *
   * @param paramInterfaceLink (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "paramInterfacesLinkParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_LINK_PARAM_INTERFACE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> paramInterfacesLinkParamInterface(
      @Parameter(name = "ParamInterfaceLink", description = "", required = true) @Valid @RequestBody
          ParamInterfaceLink paramInterfaceLink);

  String PATH_PARAM_INTERFACES_LIST_PARAM_INTERFACE_LINKS = "/api/param-interfaces/links";

  /**
   * GET /api/param-interfaces/links
   *
   * @param inspectionParameterCode (optional)
   * @param paramInterfaceCode (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "paramInterfacesListParamInterfaceLinks",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(
                          implementation = ParamInterfacesListParamInterfaceLinks200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_LIST_PARAM_INTERFACE_LINKS,
      produces = {"application/json"})
  ResponseEntity<ParamInterfacesListParamInterfaceLinks200Response>
      paramInterfacesListParamInterfaceLinks(
          @Parameter(name = "inspectionParameterCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "inspectionParameterCode", required = false)
              @Nullable
              String inspectionParameterCode,
          @Parameter(name = "paramInterfaceCode", description = "", in = ParameterIn.QUERY)
              @Valid
              @RequestParam(value = "paramInterfaceCode", required = false)
              @Nullable
              String paramInterfaceCode);

  String PATH_PARAM_INTERFACES_LIST_PARAM_INTERFACES = "/api/param-interfaces";

  /**
   * GET /api/param-interfaces
   *
   * @param page (optional)
   * @param pageSize (optional)
   * @param keyword (optional)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "paramInterfacesListParamInterfaces",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema =
                      @Schema(implementation = ParamInterfacesListParamInterfaces200Response.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.GET,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_LIST_PARAM_INTERFACES,
      produces = {"application/json"})
  ResponseEntity<ParamInterfacesListParamInterfaces200Response> paramInterfacesListParamInterfaces(
      @Parameter(name = "page", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "page", required = false)
          @Nullable
          Integer page,
      @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "pageSize", required = false)
          @Nullable
          Integer pageSize,
      @Parameter(name = "keyword", description = "", in = ParameterIn.QUERY)
          @Valid
          @RequestParam(value = "keyword", required = false)
          @Nullable
          String keyword);

  String PATH_PARAM_INTERFACES_UNLINK_PARAM_INTERFACE = "/api/param-interfaces/links";

  /**
   * DELETE /api/param-interfaces/links
   *
   * @param paramInterfacesUnlinkParamInterfaceRequest (required)
   * @return There is no content to send for this request, but the headers may be useful. (status
   *     code 204) or An unexpected error response. (status code 200)
   */
  @Operation(
      operationId = "paramInterfacesUnlinkParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "204",
            description =
                "There is no content to send for this request, but the headers may be useful. "),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.DELETE,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_UNLINK_PARAM_INTERFACE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<Void> paramInterfacesUnlinkParamInterface(
      @Parameter(
              name = "ParamInterfacesUnlinkParamInterfaceRequest",
              description = "",
              required = true)
          @Valid
          @RequestBody
          ParamInterfacesUnlinkParamInterfaceRequest paramInterfacesUnlinkParamInterfaceRequest);

  String PATH_PARAM_INTERFACES_UPDATE_PARAM_INTERFACE = "/api/param-interfaces/{code}";

  /**
   * PUT /api/param-interfaces/{code}
   *
   * @param code (required)
   * @param updateParamInterfaceRequest (required)
   * @return The request has succeeded. (status code 200) or An unexpected error response. (status
   *     code 200)
   */
  @Operation(
      operationId = "paramInterfacesUpdateParamInterface",
      tags = {"param-interfaces"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description = "The request has succeeded.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ParamInterface.class))
            }),
        @ApiResponse(
            responseCode = "default",
            description = "An unexpected error response.",
            content = {
              @Content(
                  mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponse.class))
            })
      })
  @RequestMapping(
      method = RequestMethod.PUT,
      value = ParamInterfacesApi.PATH_PARAM_INTERFACES_UPDATE_PARAM_INTERFACE,
      produces = {"application/json"},
      consumes = {"application/json"})
  ResponseEntity<ParamInterface> paramInterfacesUpdateParamInterface(
      @Parameter(name = "code", description = "", required = true, in = ParameterIn.PATH)
          @PathVariable("code")
          String code,
      @Parameter(name = "UpdateParamInterfaceRequest", description = "", required = true)
          @Valid
          @RequestBody
          UpdateParamInterfaceRequest updateParamInterfaceRequest);
}
