package io.xr.lab.shared.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;
import jakarta.validation.constraints.*;
import java.util.*;

@JsonIgnoreProperties(
    value =
        "kind", // ignore manually set kind, it will be automatically generated by Jackson during
    // serialization
    allowSetters = true // allows the kind to be set during deserialization
    )
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "kind",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AuthStateAnonymous.class, name = "anonymous"),
  @JsonSubTypes.Type(value = AuthStateAuthenticated.class, name = "authenticated"),
  @JsonSubTypes.Type(value = AuthStateAwaitingTenant.class, name = "awaiting_tenant"),
  @JsonSubTypes.Type(value = AuthStateIdle.class, name = "idle")
})
@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2026-08-20T13:31:51.674991500+08:00[Asia/Shanghai]",
    comments = "Generator version: 7.24.0")
public interface AuthState {}
